CREATE TABLE IF NOT EXISTS Users (
    Id BIGSERIAL PRIMARY KEY,
    Login VARCHAR(50) NOT NULL,
    Password VARCHAR(1000) NOT NULL,
    FullName VARCHAR(255),
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UpdatedAt TIMESTAMP WITHOUT TIME ZONE
);